In [3]:
l = [1234,8765,34567,23456,-23456]

In [4]:
l

[1234, 8765, 34567, 23456, -23456]

In [5]:
import numpy as np

In [6]:
a = np.array(l)

In [7]:
a

array([  1234,   8765,  34567,  23456, -23456])

In [9]:
b = np.array([12, 455, "abc", True])

In [10]:
b

array(['12', '455', 'abc', 'True'], dtype='<U21')

In [11]:
print(b)

['12' '455' 'abc' 'True']


In [12]:
l.pop()

-23456

In [13]:
l

[1234, 8765, 34567, 23456]

In [14]:
a.mean()

8913.2

---

In [15]:
l[:]

[1234, 8765, 34567, 23456]

In [16]:
l[2:]

[34567, 23456]

In [17]:
a[2:]

array([ 34567,  23456, -23456])

In [18]:
a[2:4]

array([34567, 23456])

In [19]:
b = a[2:4]

In [20]:
b

array([34567, 23456])

In [21]:
b[0]

34567

In [22]:
b[:] = 111

In [23]:
b

array([111, 111])

In [24]:
a

array([  1234,   8765,    111,    111, -23456])

In [25]:
c = a.copy()

In [26]:
c

array([  1234,   8765,    111,    111, -23456])

In [27]:
c[0] = 0

In [28]:
c

array([     0,   8765,    111,    111, -23456])

In [29]:
a

array([  1234,   8765,    111,    111, -23456])

---

In [37]:
a = [1, 2, 3]

In [38]:
b = [4, 5, 6]

In [39]:
#Operations with two lists
ab = []

for i in range(0, len(a)):
    ab.append(a[i] * b[i])
    
ab

[4, 10, 18]

In [40]:
# list comprehensions
# list comprehension provides a concise way to create lists.
# common applications are to make new lists where each element 
# is the result of some operations applied to each member of 
# another sequence or iterable, or to create a subsequence of 
# those elements that satisfy a certain condition.

doubled_a = [i * 2 for i in a]
doubled_a



[2, 4, 6]

In [ ]:
# round()
# max()
# min()